#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model Baio232805_Assign2_Part2
 Dymola Version 2023 (64-bit), 2022-04-13 translated this at Sat Aug  3 23:57:55 2024

   */

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    6
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    87
#define NWP_   49
#define NP_    62
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1814677868
#define NHash2_ 649507828
#define NHash3_ 0
#define NI_    0
#define NRelF_ 10
#define NRel_  10
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    49
#define SizePre_ 2
#define SizeEq_ 7
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 2
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 10
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Baio232805_Assign2_Part2";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection
#if defined(DynSimStruct)
DYNX(W_,56) = 288.15;
DYNX(W_,58) = 6E-05;
DYNX(W_,60) = 288.15;
DYNX(W_,61) = 288.15;
DYNX(W_,71) = 288.15;
DYNX(W_,75) = 0.8;
DYNX(W_,49) = 6E-05;
DYNX(W_,78) = 288.15;
DYNX(W_,79) = 288.15;
DYNX(W_,81) = 288.15;
DYNX(W_,85) = 0;
DYNX(F_,5) = 0.736967;
#endif

InitialSection
#if defined(DynSimStruct)
DYNX(W_,2) = false;
DYNX(W_,16) = true;
DYNX(W_,17) = true;
DYNX(W_,23) = true;
DYNX(W_,24) = false;
DYNX(W_,27) = false;
DYNX(W_,40) = true;
DYNX(W_,41) = true;
DYNX(W_,47) = true;
DYNX(W_,48) = true;
DYNX(W_,28) = 1;
DYNX(W_,1) = 0.15995200000000004;
DYNX(W_,13) = 0.1;
DYNX(W_,26) = 0;
DYNX(W_,0) = 0;
DYNX(W_,29) = 0;
DYNX(W_,25) = 0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
AssertModelica(DYNX(DP_,47) > DYNX(DP_,46),"hysteresis.uHigh > hysteresis.uLow",
   "Hysteresis limits wrong (uHigh <= uLow)");
AssertModelica(DYNX(DP_,54) > DYNX(DP_,53),"Gear_unit_T_range.uHigh > Gear_unit_T_range.uLow",
   "Hysteresis limits wrong (uHigh <= uLow)");
BoundParameterSection
DYNX(W_,3) = DYNX(DP_,4);
DYNX(W_,4) = DYNX(DP_,5);
DYNX(W_,5) = DYNX(DP_,6);
DYNX(W_,6) = DYNX(DP_,7);
DYNX(W_,7) = DYNX(DP_,8);
DYNX(W_,8) = DYNX(DP_,4);
DYNX(W_,9) = DYNX(DP_,5);
DYNX(W_,10) = DYNX(DP_,6);
DYNX(W_,11) = DYNX(DP_,7);
DYNX(W_,12) = DYNX(DP_,8);
DYNX(DYNhelp,0) = divinvGuarded(DYNX(W_,13),"pipe.V_flowLaminar");
DYNX(W_,14) = DYNX(DYNhelp,0)*DYNX(DP_,11)*DYNX(DP_,12);
DYNX(W_,18) = DYNX(DP_,17);
DYNX(W_,19) = DYNX(DP_,18);
DYNX(W_,20) = DYNX(DP_,19);
DYNX(W_,21) = DYNX(DP_,20);
DYNX(W_,22) = DYNX(DP_,21);
DYNX(W_,30) = DYNX(DP_,27);
AssertModelica(fabs(DYNX(W_,30)-DYNX(W_,18)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.rho-Source_tank.flowPort.medium.rho) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,31) = DYNX(DP_,28);
AssertModelica(fabs(DYNX(W_,31)-DYNX(W_,19)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.cp-Source_tank.flowPort.medium.cp) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,32) = DYNX(DP_,29);
AssertModelica(fabs(DYNX(W_,32)-DYNX(W_,20)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.cv-Source_tank.flowPort.medium.cv) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,33) = DYNX(DP_,30);
AssertModelica(fabs(DYNX(W_,33)-DYNX(W_,21)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.lambda-Source_tank.flowPort.medium.lambda) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,34) = DYNX(DP_,31);
AssertModelica(fabs(DYNX(W_,34)-DYNX(W_,22)) <= 0.0,"abs(volumeFlow.flowPort_a.medium.nu-Source_tank.flowPort.medium.nu) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,35) = DYNX(DP_,27);
AssertModelica(fabs(DYNX(W_,35)-DYNX(W_,3)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.rho-pipe.flowPort_a.medium.rho) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,36) = DYNX(DP_,28);
AssertModelica(fabs(DYNX(W_,36)-DYNX(W_,4)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.cp-pipe.flowPort_a.medium.cp) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,37) = DYNX(DP_,29);
AssertModelica(fabs(DYNX(W_,37)-DYNX(W_,5)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.cv-pipe.flowPort_a.medium.cv) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,38) = DYNX(DP_,30);
AssertModelica(fabs(DYNX(W_,38)-DYNX(W_,6)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.lambda-pipe.flowPort_a.medium.lambda) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,39) = DYNX(DP_,31);
AssertModelica(fabs(DYNX(W_,39)-DYNX(W_,7)) <= 0.0,"abs(volumeFlow.flowPort_b.medium.nu-pipe.flowPort_a.medium.nu) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,42) = DYNX(DP_,34);
AssertModelica(fabs(DYNX(W_,8)-DYNX(W_,42)) <= 0.0,"abs(pipe.flowPort_b.medium.rho-Storage_tank.flowPort.medium.rho) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,43) = DYNX(DP_,35);
AssertModelica(fabs(DYNX(W_,9)-DYNX(W_,43)) <= 0.0,"abs(pipe.flowPort_b.medium.cp-Storage_tank.flowPort.medium.cp) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,44) = DYNX(DP_,36);
AssertModelica(fabs(DYNX(W_,10)-DYNX(W_,44)) <= 0.0,"abs(pipe.flowPort_b.medium.cv-Storage_tank.flowPort.medium.cv) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,45) = DYNX(DP_,37);
AssertModelica(fabs(DYNX(W_,11)-DYNX(W_,45)) <= 0.0,"abs(pipe.flowPort_b.medium.lambda-Storage_tank.flowPort.medium.lambda) <= 0.0",
   "Parameters in connected connectors must be equal");
DYNX(W_,46) = DYNX(DP_,38);
AssertModelica(fabs(DYNX(W_,12)-DYNX(W_,46)) <= 0.0,"abs(pipe.flowPort_b.medium.nu-Storage_tank.flowPort.medium.nu) <= 0.0",
   "Parameters in connected connectors must be equal");
InitialSection
InitialStartSection
InitialStartSection2
DYNX(W_,63) = DYNX(DP_,5)*DYNX(DP_,9);
DYNX(W_,65) = DYNX(DP_,28)*DYNX(DP_,32);
DYNX(W_,72) = DYNX(DP_,22);
DYNX(W_,77) = DYNX(DP_,32);
DYNX(W_,82) = DYNX(DP_,39);
DYNX(X_,0) = DYNX(DP_,9);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,0) = DYNX(W_,52);
DYNX(Aux_,1) = DYNX(W_,51);
InitialSection
InitialSection2
  AssertModelica(DYNX(DP_,12) > 0.1,"pipe.V_flowNominal > 0.1", "SimpleFriction: V_flowNominal has to be > V_flowLaminar!");
  AssertModelica(DYNX(DP_,13) >= DYNX(W_,14),"pipe.dpNominal >= pipe.dpNomMin", 
    "SimpleFriction: dpNominal has to be > dpLaminar/V_flowLaminar*V_flowNominal!");
  DYNX(W_,15) = divGuarded(DYNX(DP_,13)-DYNX(W_,14),"pipe.dpNominal-pipe.dpNomMin",
    sqr(DYNX(DP_,12)-0.1),"(pipe.V_flowNominal-0.1)^2");
DYNX(X_,1) = DYNX(DP_,17)*DYNX(DP_,23)*DYNX(W_,75);
DYNX(W_,72) = DYNX(DP_,22);
DYNX(W_,74) = DYNX(W_,72)*DYNX(DP_,18);
DYNX(X_,2) = DYNX(X_,1)*DYNX(W_,74);
DYNX(X_,0) = DYNX(DP_,9);
DYNX(X_,3) = DYNX(DP_,34)*DYNX(DP_,40)*DYNX(W_,85);
DYNX(W_,82) = DYNX(DP_,39);
DYNX(W_,83) = DYNX(W_,82)*DYNX(DP_,35);
DYNX(X_,4) = DYNX(X_,3)*DYNX(W_,83);
InitialBoundSection
DYNX(Aux_,0) = DYNX(DP_,55);
DYNX(Aux_,1) = DYNX(DP_,48);
InitialSection
InitialSection2
DYNX(W_,52) = DYNX(Aux_,0);
DYNX(W_,51) = DYNX(Aux_,1);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,52) =  NOT PRE(DYNX(W_,52), 0) AND Greater(DYNX(X_,5),"Gear_unit_T_range.u",
   DYNX(DP_,54),"Gear_unit_T_range.uHigh", 0) OR PRE(DYNX(W_,52), 0) AND 
  GreaterEqual(DYNX(X_,5),"Gear_unit_T_range.u", DYNX(DP_,53),"Gear_unit_T_range.uLow",
   1);
DYNX(W_,49) = IF DYNX(W_,52) THEN DYNX(DP_,51) ELSE DYNX(DP_,52);
DYNX(F_,1) =  -DYNX(W_,49)*DYNX(DP_,27);
if (NewParameters_) {
DYNX(DYNhelp,1) = divinvGuarded(DYNX(DP_,4),"pipe.medium.rho");
}
DYNX(W_,58) =  -DYNX(DYNhelp,1)*DYNX(F_,1);
DYNX(W_,63) = DYNX(DP_,5)*DYNX(X_,0);
 /* Linear system of equations to solve. */
DYNX(W_,74) = RememberSimple_(DYNX(W_,74), 0);
SolveScalarLinear( -DYNX(X_,1)," -Source_tank.m",  -DYNX(X_,2)," -Source_tank.H",
   DYNX(W_,74),"Source_tank.h");
 /* End of Equation Block */ 

DYNX(DYNhelp,2) = 1.0+DYNX(F_,1) > 1.0;
DYNX(W_,65) = IF DYNX(DYNhelp,2) THEN DYNX(W_,63) ELSE DYNX(W_,74);
if (NewParameters_) {
DYNX(DYNhelp,3) = divinvGuarded(DYNX(DP_,5),"pipe.medium.cp");
}
DYNX(W_,60) = DYNX(DYNhelp,3)*DYNX(W_,65);
 /* Linear system of equations to solve. */
DYNX(W_,83) = RememberSimple_(DYNX(W_,83), 1);
SolveScalarLinear( -DYNX(X_,3)," -Storage_tank.m",  -DYNX(X_,4)," -Storage_tank.H",
   DYNX(W_,83),"Storage_tank.h");
 /* End of Equation Block */ 

DYNX(W_,67) = IF DYNX(DYNhelp,2) THEN DYNX(W_,83) ELSE DYNX(W_,63);
DYNX(W_,61) = DYNX(DYNhelp,3)*DYNX(W_,67);
DYNX(W_,62) = IF DYNX(W_,58) >= 0 THEN DYNX(X_,0)-DYNX(W_,60) ELSE DYNX(W_,61)-
  DYNX(X_,0);
DYNX(W_,56) = DYNX(X_,0)-(IF DYNX(W_,58) > 0 THEN 1 ELSE IF DYNX(W_,58) < 0
   THEN -1 ELSE 0)*(1-DYNX(DP_,10))*DYNX(W_,62);
DYNX(W_,55) = DYNX(X_,5)-DYNX(W_,56);
DYNX(W_,54) = DYNX(DP_,3)*DYNX(W_,55);
DYNX(W_,53) =  -DYNX(DP_,0)*(1+DYNX(DP_,2)*(DYNX(X_,5)-DYNX(DP_,1)));
DYNX(W_,86) =  -(DYNX(W_,54)+DYNX(W_,53));
 /* Linear system of equations to solve. */
DYNX(F_,5) = RememberSimple_(DYNX(F_,5), 2);
SolveScalarLinearParametric(DYNX(DP_,56),"Gear_wall_capacitance.C", DYNX(W_,86),
  "Gear_wall_capacitance.port.Q_flow", DYNX(F_,5),"der(Gear_wall_capacitance.T)");
 /* End of Equation Block */ 

DYNX(DYNhelp,4) = DYNX(F_,1) >= 0;
DYNX(F_,2) = IF DYNX(DYNhelp,4) THEN DYNX(W_,63)*DYNX(F_,1) ELSE DYNX(W_,74)*
  DYNX(F_,1);
DYNX(W_,68) = IF DYNX(DYNhelp,4) THEN DYNX(W_,83)*DYNX(F_,1) ELSE DYNX(W_,63)*
  DYNX(F_,1);
DYNX(W_,69) = IF Greater(DYNX(W_,58),"pipe.volumeFlow", 0.1,"0.1", 2) THEN 10.0*
  DYNX(DP_,11)*DYNX(W_,58)+DYNX(W_,15)*sqr(DYNX(W_,58)-0.1) ELSE IF Less(
  DYNX(W_,58),"pipe.volumeFlow", -0.1,"-0.1", 3) THEN 10.0*DYNX(DP_,11)*
  DYNX(W_,58)-DYNX(W_,15)*sqr(0.1+DYNX(W_,58)) ELSE 10.0*DYNX(DP_,11)*
  DYNX(W_,58);
DYNX(W_,70) = DYNX(DP_,14)*DYNX(W_,58)*DYNX(W_,69);
DYNX(W_,59) = DYNX(W_,54)+DYNX(W_,70);
 /* Linear system of equations to solve. */
DYNX(F_,0) = RememberSimple_(DYNX(F_,0), 3);
SolveScalarLinearParametric((-0.15995200000000004)*DYNX(DP_,6),"(-0.15995200000000004)*pipe.medium.cv",
    -(DYNX(W_,68)-DYNX(F_,2)+DYNX(W_,59))," -(pipe.flowPort_b.H_flow-( -pipe.flowPort_a.H_flow)+pipe.Q_flow)",
   DYNX(F_,0),"der(pipe.T)");
 /* End of Equation Block */ 

DYNX(F_,3) =  -DYNX(F_,1);
if (NewParameters_) {
DYNX(DYNhelp,5) = divinvGuarded(DYNX(DP_,35),"Storage_tank.medium.cp");
}
DYNX(W_,82) = DYNX(DYNhelp,5)*DYNX(W_,83);
DYNX(W_,51) =  NOT PRE(DYNX(W_,51), 1) AND Greater(DYNX(W_,82),"hysteresis.u", 
  DYNX(DP_,47),"hysteresis.uHigh", 4) OR PRE(DYNX(W_,51), 1) AND GreaterEqual(
  DYNX(W_,82),"hysteresis.u", DYNX(DP_,46),"hysteresis.uLow", 5);
DYNX(W_,50) = IF DYNX(W_,51) THEN DYNX(DP_,49) ELSE DYNX(DP_,50);
DYNX(W_,84) = DYNX(W_,50)*(1+DYNX(DP_,45)*(DYNX(W_,82)-DYNX(DP_,44)));
DYNX(F_,4) = DYNX(W_,84)-DYNX(W_,68);

AcceptedSection1
 /* Linear system of equations to solve. */
DYNX(W_,75) = RememberSimple_(DYNX(W_,75), 4);
SolveScalarLinearParametric( -DYNX(DP_,17)*DYNX(DP_,23)," -Source_tank.medium.rho*Source_tank.ATank",
    -DYNX(X_,1)," -Source_tank.m", DYNX(W_,75),"Source_tank.level");
 /* End of Equation Block */ 

AssertModelica(GreaterEqual(DYNX(W_,75),"Source_tank.level", 0,"0", 6),
  "Source_tank.level >= 0", "Tank got empty!");
 /* Linear system of equations to solve. */
DYNX(W_,85) = RememberSimple_(DYNX(W_,85), 5);
SolveScalarLinearParametric( -DYNX(DP_,34)*DYNX(DP_,40)," -Storage_tank.medium.rho*Storage_tank.ATank",
    -DYNX(X_,3)," -Storage_tank.m", DYNX(W_,85),"Storage_tank.level");
 /* End of Equation Block */ 

AssertModelica(GreaterEqual(DYNX(W_,85),"Storage_tank.level", 0,"0", 7),
  "Storage_tank.level >= 0", "Tank got empty!");

AssertModelica(LessEqual(DYNX(W_,75),"Source_tank.level", DYNX(DP_,24),
  "Source_tank.hTank", 8),"Source_tank.level <= Source_tank.hTank", 
  "Tank got full!");
AssertModelica(LessEqual(DYNX(W_,85),"Storage_tank.level", DYNX(DP_,41),
  "Storage_tank.hTank", 9),"Storage_tank.level <= Storage_tank.hTank", 
  "Tank got full!");
AcceptedSection2
if (NewParameters_) {
DYNX(DYNhelp,6) = divinvGuarded(DYNX(DP_,18),"Source_tank.medium.cp");
}
DYNX(W_,72) = DYNX(DYNhelp,6)*DYNX(W_,74);
DYNX(W_,57) = DYNX(W_,69)+DYNX(DP_,4)*DYNX(DP_,16)*DYNX(DP_,15);
if (NewParameters_) {
DYNX(DYNhelp,7) = divinvGuarded(DYNX(DP_,40),"Storage_tank.ATank");
}
DYNX(W_,66) = DYNX(DP_,42)+DYNX(DYNhelp,7)*DYNX(X_,3)*DYNX(DP_,43);
DYNX(W_,64) = DYNX(W_,57)+DYNX(W_,66);
DYNX(W_,71) = DYNX(DYNhelp,6)*DYNX(W_,65);
if (NewParameters_) {
DYNX(DYNhelp,8) = divinvGuarded(DYNX(DP_,23),"Source_tank.ATank");
}
DYNX(W_,73) = DYNX(DP_,25)+DYNX(DYNhelp,8)*DYNX(X_,1)*DYNX(DP_,26);
DYNX(W_,76) = DYNX(W_,73)-DYNX(W_,64);
 /* Linear system of equations to solve. */
DYNX(W_,77) = RememberSimple_(DYNX(W_,77), 6);
SolveScalarLinearParametric( -DYNX(DP_,28)," -volumeFlow.medium.cp",  -
  DYNX(W_,65)," -volumeFlow.h", DYNX(W_,77),"volumeFlow.T");
 /* End of Equation Block */ 

if (NewParameters_) {
DYNX(DYNhelp,9) = divinvGuarded(DYNX(DP_,28),"volumeFlow.medium.cp");
}
DYNX(W_,78) = DYNX(DYNhelp,9)*DYNX(W_,65);
DYNX(W_,79) = DYNX(DYNhelp,9)*DYNX(W_,65);
DYNX(W_,80) = IF DYNX(W_,49) >= 0 THEN DYNX(W_,77)-DYNX(W_,78) ELSE DYNX(W_,79)-
  DYNX(W_,77);
DYNX(W_,81) = DYNX(DYNhelp,5)*DYNX(W_,67);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("fixedHeatFlow.Q_flow", "Fixed heat flow rate at port [W]", 0, \
2210.9, 0.0,0.0,0.0,0,560)
DeclareParameter("fixedHeatFlow.T_ref", "Reference temperature [K|degC]", 1, \
293.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("fixedHeatFlow.alpha", "Temperature coefficient of heat flow rate [1/K]",\
 2, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("fixedHeatFlow.port.T", "Port temperature [K|degC]", \
"Gear_wall_capacitance.T", 1, 1, 5, 4)
DeclareVariable("fixedHeatFlow.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 53, 0.0, 0.0,0.0,0.0,0,776)
DeclareAlias2("Gear_unit_T.T", "Absolute temperature as output signal [K]", \
"Gear_wall_capacitance.T", 1, 1, 5, 0)
DeclareAlias2("Gear_unit_T.port.T", "Port temperature [K|degC]", \
"Gear_wall_capacitance.T", 1, 1, 5, 4)
DeclareVariable("Gear_unit_T.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 0, 0, 0.0,0.0,0.0,0,777)
DeclareVariable("Water_convection.Q_flow", "Heat flow rate from solid -> fluid [W]",\
 54, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("Water_convection.dT", "= solid.T - fluid.T [K,]", 55, 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("Water_convection.Gc", "Signal representing the convective thermal conductance in [W/K] [W/K]",\
 "Convective_conductance.k", 1, 7, 3, 0)
DeclareAlias2("Water_convection.solid.T", "Port temperature [K|degC]", \
"Gear_wall_capacitance.T", 1, 1, 5, 4)
DeclareAlias2("Water_convection.solid.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "Water_convection.Q_flow", 1, 5, 54, 132)
DeclareVariable("Water_convection.fluid.T", "Port temperature [K|degC]", 56, \
288.15, 0.0,1E+100,300.0,0,520)
DeclareAlias2("Water_convection.fluid.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "Water_convection.Q_flow", -1, 5, 54, 132)
DeclareParameter("Convective_conductance.k", "Constant output value [W/K]", 3, 300,\
 0.0,0.0,0.0,0,560)
DeclareAlias2("Convective_conductance.y", "Connector of Real output signal [W/K]",\
 "Convective_conductance.k", 1, 7, 3, 0)
DeclareParameter("pipe.medium.rho", "Density [kg/m3|g/cm3]", 4, 999.7, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("pipe.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 5, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 6, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.medium.lambda", "Thermal conductivity [W/(m.K)]", 7, \
0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.medium.nu", "Kinematic viscosity [m2/s]", 8, 1.307E-06, \
0.0,1E+100,0.0,0,560)
DeclareVariable("pipe.m", "Mass of medium [kg]", 1, 0.15995200000000004, 0.0,\
1E+100,0.0,0,513)
DeclareParameter("pipe.T0", "Initial temperature of medium [K|degC]", 9, 283.15,\
 0.0,1E+100,300.0,0,560)
DeclareVariable("pipe.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 2, false, 0.0,0.0,0.0,0,515)
DeclareParameter("pipe.tapT", "Defines temperature of heatPort between inlet and outlet temperature",\
 10, 1, 0.0,1.0,0.0,0,560)
DeclareVariable("pipe.dp", "Pressure drop a->b [Pa|bar]", 57, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.V_flow", "Volume flow a->b [m3/s]", 58, 6E-05, 0.0,0.0,0.0,\
0,512)
DeclareVariable("pipe.Q_flow", "Heat exchange with ambient [W]", 59, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("pipe.T", "Outlet temperature of medium [K|degC]", 0, 0.0, 0.0,\
1E+100,300.0,0,544)
DeclareDerivative("pipe.der(T)", "der(Outlet temperature of medium) [K/s]", 0, \
0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.T_a", "Temperature at flowPort_a [K|degC]", 60, 288.15, \
0.0,1E+100,300.0,0,512)
DeclareVariable("pipe.T_b", "Temperature at flowPort_b [K|degC]", 61, 288.15, \
0.0,1E+100,300.0,0,512)
DeclareVariable("pipe.dT", "Temperature increase of coolant in flow direction [K,]",\
 62, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipe.T_q", "Temperature relevant for heat exchange with ambient [K|degC]",\
 "Water_convection.fluid.T", 1, 5, 56, 0)
DeclareVariable("pipe.h", "Medium's specific enthalpy [J/kg]", 63, 0.0, 0.0,0.0,\
0.0,0,2560)
DeclareVariable("pipe.flowPort_a.medium.rho", "Density [kg/m3|g/cm3]", 3, 0.0, \
0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 4, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 5, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 6, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_a.medium.nu", "Kinematic viscosity [m2/s]", 7, \
0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_a.p", "[Pa|bar]", 64, 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("pipe.flowPort_a.m_flow", "[kg/s]", "Source_tank.der(m)", -1, 6, 1,\
 132)
DeclareVariable("pipe.flowPort_a.h", "[J/kg]", 65, 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("pipe.flowPort_a.H_flow", "[W]", "Source_tank.der(H)", -1, 6, 2, 132)
DeclareVariable("pipe.flowPort_b.medium.rho", "Density [kg/m3|g/cm3]", 8, 0.0, \
0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 9, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 10, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 11, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("pipe.flowPort_b.medium.nu", "Kinematic viscosity [m2/s]", 12, \
0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("pipe.flowPort_b.p", "[Pa|bar]", 66, 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("pipe.flowPort_b.m_flow", "[kg/s]", "Source_tank.der(m)", 1, 6, 1,\
 132)
DeclareVariable("pipe.flowPort_b.h", "[J/kg]", 67, 0.0, 0.0,0.0,0.0,0,520)
DeclareVariable("pipe.flowPort_b.H_flow", "[W]", 68, 0.0, 0.0,0.0,0.0,0,776)
DeclareVariable("pipe.V_flowLaminar", "Laminar volume flow [m3/s]", 13, 0.1, \
1E-60,1E+100,0.0,0,513)
DeclareParameter("pipe.dpLaminar", "Laminar pressure drop [Pa|bar]", 11, 0.1, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipe.V_flowNominal", "Nominal volume flow [m3/s]", 12, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipe.dpNominal", "Nominal pressure drop [Pa|bar]", 13, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("pipe.frictionLoss", "Part of friction losses fed to medium [1]",\
 14, 0, 0.0,1.0,0.0,0,560)
DeclareVariable("pipe.pressureDrop", "[Pa|bar]", 69, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("pipe.volumeFlow", "[m3/s]", "pipe.V_flow", 1, 5, 58, 0)
DeclareVariable("pipe.Q_friction", "[W]", 70, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("pipe.dpNomMin", "[Pa|bar]", 14, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("pipe.k", "[Pa.s2/m6]", 15, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("pipe.useHeatPort", "= true, if HeatPort is enabled [:#(type=Boolean)]",\
 16, true, 0.0,0.0,0.0,0,1539)
DeclareParameter("pipe.h_g", "Geodetic height (height difference from flowPort_a to flowPort_b) [m]",\
 15, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("pipe.g", "Gravitation [m/s2]", 16, 9.80665, 0.0,1E+100,0.0,0,560)
DeclareAlias2("pipe.heatPort.T", "Port temperature [K|degC]", "Water_convection.fluid.T", 1,\
 5, 56, 4)
DeclareAlias2("pipe.heatPort.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "Water_convection.Q_flow", 1, 5, 54, 132)
DeclareAlias2("pipe.Q_flowHeatPort", "Heat flow at conditional heatPort [W]", \
"Water_convection.Q_flow", 1, 5, 54, 1024)
DeclareParameter("Source_tank.medium.rho", "Density [kg/m3|g/cm3]", 17, 999.7, \
0.0,1E+100,0.0,0,560)
DeclareParameter("Source_tank.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 18, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("Source_tank.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 19, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("Source_tank.medium.lambda", "Thermal conductivity [W/(m.K)]", 20,\
 0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("Source_tank.medium.nu", "Kinematic viscosity [m2/s]", 21, \
1.307E-06, 0.0,1E+100,0.0,0,560)
DeclareParameter("Source_tank.T0", "Initial temperature of medium [K|degC]", 22,\
 283.15, 0.0,1E+100,300.0,0,560)
DeclareVariable("Source_tank.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 17, true, 0.0,0.0,0.0,0,515)
DeclareVariable("Source_tank.T_port", "Temperature at flowPort_a [K|degC]", 71, \
288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("Source_tank.T", "Outlet temperature of medium [K|degC]", 72, \
0.0, 0.0,1E+100,300.0,0,512)
DeclareVariable("Source_tank.flowPort.medium.rho", "Density [kg/m3|g/cm3]", 18, \
0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("Source_tank.flowPort.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 19, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Source_tank.flowPort.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 20, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Source_tank.flowPort.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 21, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Source_tank.flowPort.medium.nu", "Kinematic viscosity [m2/s]", 22,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("Source_tank.flowPort.p", "[Pa|bar]", 73, 0.0, 0.0,0.0,0.0,0,520)
DeclareAlias2("Source_tank.flowPort.m_flow", "[kg/s]", "Source_tank.der(m)", 1, 6,\
 1, 132)
DeclareAlias2("Source_tank.flowPort.h", "[J/kg]", "pipe.flowPort_a.h", 1, 5, 65,\
 4)
DeclareAlias2("Source_tank.flowPort.H_flow", "[W]", "Source_tank.der(H)", 1, 6, 2,\
 132)
DeclareVariable("Source_tank.Exchange", "Exchange of medium via flowport [:#(type=Boolean)]",\
 23, true, 0.0,0.0,0.0,0,1539)
DeclareVariable("Source_tank.h", "Specific enthalpy in the volume [J/kg]", 74, \
0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("Source_tank.ATank", "Cross section of tank [m2]", 23, 0.01, \
0.0,0.0,0.0,0,560)
DeclareParameter("Source_tank.hTank", "Height of tank [m]", 24, 0.8, 0.0,0.0,0.0,\
0,560)
DeclareParameter("Source_tank.pAmbient", "Ambient pressure [Pa|Pa]", 25, 101325,\
 0.0,0.0,0.0,0,560)
DeclareParameter("Source_tank.g", "Gravitation [m/s2]", 26, 9.80665, 0.0,1E+100,\
0.0,0,560)
DeclareVariable("Source_tank.useHeatPort", "= true, if HeatPort is enabled [:#(type=Boolean)]",\
 24, false, 0.0,0.0,0.0,0,1539)
DeclareState("Source_tank.m", "Mass of medium in tank [kg]", 1, 0.0, 0.0,1E+100,\
0.0,0,544)
DeclareDerivative("Source_tank.der(m)", "der(Mass of medium in tank) [kg/s]", 1,\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("Source_tank.H", "Enthalpy of medium [J]", 2, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("Source_tank.der(H)", "der(Enthalpy of medium) [W]", 2, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("Source_tank.Q_flow", "Heat flow at the optional heatPort [W]", 25,\
 0, 0.0,0.0,0.0,0,2561)
DeclareVariable("Source_tank.level", "Level of medium in tank [m]", 75, 0.8, \
0.0,0.0,0.0,0,528)
DeclareAlias2("Source_tank.TTank", "Temperature of medium in tank [K|degC]", \
"Source_tank.T", 1, 5, 72, 0)
DeclareParameter("volumeFlow.medium.rho", "Density [kg/m3|g/cm3]", 27, 999.7, \
0.0,1E+100,0.0,0,560)
DeclareParameter("volumeFlow.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 28, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("volumeFlow.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 29, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("volumeFlow.medium.lambda", "Thermal conductivity [W/(m.K)]", 30,\
 0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("volumeFlow.medium.nu", "Kinematic viscosity [m2/s]", 31, \
1.307E-06, 0.0,1E+100,0.0,0,560)
DeclareVariable("volumeFlow.m", "Mass of medium [kg]", 26, 0, 0.0,1E+100,0.0,0,513)
DeclareParameter("volumeFlow.T0", "Initial temperature of medium [K|degC]", 32, \
283.15, 0.0,1E+100,300.0,0,560)
DeclareVariable("volumeFlow.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 27, false, 0.0,0.0,0.0,0,515)
DeclareVariable("volumeFlow.tapT", "Defines temperature of heatPort between inlet and outlet temperature",\
 28, 1, 0.0,1.0,0.0,0,513)
DeclareVariable("volumeFlow.dp", "Pressure drop a->b [Pa|bar]", 76, 0.0, \
0.0,0.0,0.0,0,512)
DeclareVariable("volumeFlow.V_flow", "Volume flow a->b [m3/s]", 49, 6E-05, \
0.0,0.0,0.0,0,640)
DeclareVariable("volumeFlow.Q_flow", "Heat exchange with ambient [W]", 29, 0, \
0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.T", "Outlet temperature of medium [K|degC]", 77, 0.0,\
 0.0,1E+100,300.0,0,512)
DeclareVariable("volumeFlow.T_a", "Temperature at flowPort_a [K|degC]", 78, \
288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("volumeFlow.T_b", "Temperature at flowPort_b [K|degC]", 79, \
288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("volumeFlow.dT", "Temperature increase of coolant in flow direction [K,]",\
 80, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("volumeFlow.T_q", "Temperature relevant for heat exchange with ambient [K|degC]",\
 "volumeFlow.T", 1, 5, 77, 0)
DeclareAlias2("volumeFlow.h", "Medium's specific enthalpy [J/kg]", \
"pipe.flowPort_a.h", 1, 5, 65, 1024)
DeclareVariable("volumeFlow.flowPort_a.medium.rho", "Density [kg/m3|g/cm3]", 30,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 31, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 32, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 33, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_a.medium.nu", "Kinematic viscosity [m2/s]",\
 34, 0.0, 0.0,1E+100,0.0,0,513)
DeclareAlias2("volumeFlow.flowPort_a.p", "[Pa|bar]", "Source_tank.flowPort.p", 1,\
 5, 73, 4)
DeclareAlias2("volumeFlow.flowPort_a.m_flow", "[kg/s]", "Source_tank.der(m)", -1,\
 6, 1, 132)
DeclareAlias2("volumeFlow.flowPort_a.h", "[J/kg]", "pipe.flowPort_a.h", 1, 5, 65,\
 4)
DeclareAlias2("volumeFlow.flowPort_a.H_flow", "[W]", "Source_tank.der(H)", -1, 6,\
 2, 132)
DeclareVariable("volumeFlow.flowPort_b.medium.rho", "Density [kg/m3|g/cm3]", 35,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 36, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 37, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 38, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("volumeFlow.flowPort_b.medium.nu", "Kinematic viscosity [m2/s]",\
 39, 0.0, 0.0,1E+100,0.0,0,513)
DeclareAlias2("volumeFlow.flowPort_b.p", "[Pa|bar]", "pipe.flowPort_a.p", 1, 5, 64,\
 4)
DeclareAlias2("volumeFlow.flowPort_b.m_flow", "[kg/s]", "Source_tank.der(m)", 1,\
 6, 1, 132)
DeclareAlias2("volumeFlow.flowPort_b.h", "[J/kg]", "pipe.flowPort_a.h", 1, 5, 65,\
 4)
DeclareAlias2("volumeFlow.flowPort_b.H_flow", "[W]", "Source_tank.der(H)", 1, 6,\
 2, 132)
DeclareVariable("volumeFlow.useVolumeFlowInput", "Enable / disable volume flow input [:#(type=Boolean)]",\
 40, true, 0.0,0.0,0.0,0,515)
DeclareParameter("volumeFlow.constantVolumeFlow", "Volume flow rate [m3/s]", 33,\
 1, 0.0,0.0,0.0,0,560)
DeclareAlias2("volumeFlow.volumeFlow", "[m3/s]", "volumeFlow.V_flow", 1, 5, 49, 0)
DeclareAlias2("volumeFlow.internalVolumeFlow", "[m3/s]", "volumeFlow.V_flow", 1,\
 5, 49, 1024)
DeclareParameter("Storage_tank.medium.rho", "Density [kg/m3|g/cm3]", 34, 999.7, \
0.0,1E+100,0.0,0,560)
DeclareParameter("Storage_tank.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 35, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("Storage_tank.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 36, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("Storage_tank.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 37, 0.588, 0.0,0.0,0.0,0,560)
DeclareParameter("Storage_tank.medium.nu", "Kinematic viscosity [m2/s]", 38, \
1.307E-06, 0.0,1E+100,0.0,0,560)
DeclareParameter("Storage_tank.T0", "Initial temperature of medium [K|degC]", 39,\
 278.15, 0.0,1E+100,300.0,0,560)
DeclareVariable("Storage_tank.T0fixed", "Initial temperature guess value or fixed [:#(type=Boolean)]",\
 41, true, 0.0,0.0,0.0,0,515)
DeclareVariable("Storage_tank.T_port", "Temperature at flowPort_a [K|degC]", 81,\
 288.15, 0.0,1E+100,300.0,0,512)
DeclareVariable("Storage_tank.T", "Outlet temperature of medium [K|degC]", 82, \
0.0, 0.0,1E+100,300.0,0,512)
DeclareVariable("Storage_tank.flowPort.medium.rho", "Density [kg/m3|g/cm3]", 42,\
 0.0, 0.0,1E+100,0.0,0,513)
DeclareVariable("Storage_tank.flowPort.medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 43, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Storage_tank.flowPort.medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 44, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Storage_tank.flowPort.medium.lambda", "Thermal conductivity [W/(m.K)]",\
 45, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("Storage_tank.flowPort.medium.nu", "Kinematic viscosity [m2/s]",\
 46, 0.0, 0.0,1E+100,0.0,0,513)
DeclareAlias2("Storage_tank.flowPort.p", "[Pa|bar]", "pipe.flowPort_b.p", 1, 5, 66,\
 4)
DeclareAlias2("Storage_tank.flowPort.m_flow", "[kg/s]", "Source_tank.der(m)", -1,\
 6, 1, 132)
DeclareAlias2("Storage_tank.flowPort.h", "[J/kg]", "pipe.flowPort_b.h", 1, 5, 67,\
 4)
DeclareAlias2("Storage_tank.flowPort.H_flow", "[W]", "pipe.flowPort_b.H_flow", -1,\
 5, 68, 132)
DeclareVariable("Storage_tank.Exchange", "Exchange of medium via flowport [:#(type=Boolean)]",\
 47, true, 0.0,0.0,0.0,0,1539)
DeclareVariable("Storage_tank.h", "Specific enthalpy in the volume [J/kg]", 83, \
0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("Storage_tank.ATank", "Cross section of tank [m2]", 40, 0.01, \
0.0,0.0,0.0,0,560)
DeclareParameter("Storage_tank.hTank", "Height of tank [m]", 41, 0.8, 0.0,0.0,\
0.0,0,560)
DeclareParameter("Storage_tank.pAmbient", "Ambient pressure [Pa|Pa]", 42, 101325,\
 0.0,0.0,0.0,0,560)
DeclareParameter("Storage_tank.g", "Gravitation [m/s2]", 43, 9.80665, 0.0,1E+100,\
0.0,0,560)
DeclareVariable("Storage_tank.useHeatPort", "= true, if HeatPort is enabled [:#(type=Boolean)]",\
 48, true, 0.0,0.0,0.0,0,1539)
DeclareState("Storage_tank.m", "Mass of medium in tank [kg]", 3, 0.0, 0.0,1E+100,\
0.0,0,544)
DeclareDerivative("Storage_tank.der(m)", "der(Mass of medium in tank) [kg/s]", 3,\
 0.0, 0.0,0.0,0.0,0,512)
DeclareState("Storage_tank.H", "Enthalpy of medium [J]", 4, 0.0, 0.0,0.0,0.0,0,2592)
DeclareDerivative("Storage_tank.der(H)", "der(Enthalpy of medium) [W]", 4, 0.0, \
0.0,0.0,0.0,0,2560)
DeclareVariable("Storage_tank.Q_flow", "Heat flow at the optional heatPort [W]",\
 84, 0.0, 0.0,0.0,0.0,0,2560)
DeclareAlias2("Storage_tank.heatPort.T", "Port temperature [K|degC]", \
"Storage_tank.T", 1, 5, 82, 4)
DeclareAlias2("Storage_tank.heatPort.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "Storage_tank.Q_flow", 1, 5, 84, 132)
DeclareVariable("Storage_tank.level", "Level of medium in tank [m]", 85, 0, \
0.0,0.0,0.0,0,528)
DeclareAlias2("Storage_tank.TTank", "Temperature of medium in tank [K|degC]", \
"Storage_tank.T", 1, 5, 82, 0)
DeclareParameter("prescribedHeatFlow.T_ref", "Reference temperature [K|degC]", 44,\
 293.15, 0.0,1E+100,300.0,0,560)
DeclareParameter("prescribedHeatFlow.alpha", "Temperature coefficient of heat flow rate [1/K]",\
 45, 0, 0.0,0.0,0.0,0,560)
DeclareVariable("prescribedHeatFlow.Q_flow", "[W]", 50, 0.0, 0.0,0.0,0.0,0,640)
DeclareAlias2("prescribedHeatFlow.port.T", "Port temperature [K|degC]", \
"Storage_tank.T", 1, 5, 82, 4)
DeclareAlias2("prescribedHeatFlow.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 "Storage_tank.Q_flow", -1, 5, 84, 132)
DeclareParameter("hysteresis.uLow", "If y=true and u<uLow, switch to y=false", 46,\
 278.15, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresis.uHigh", "If y=false and u>uHigh, switch to y=true",\
 47, 283.15, 0.0,0.0,0.0,0,560)
DeclareParameter("hysteresis.pre_y_start", "Value of pre(y) at initial time [:#(type=Boolean)]",\
 48, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("hysteresis.u", "[K]", "Storage_tank.T", 1, 5, 82, 0)
DeclareVariable("hysteresis.y", "[:#(type=Boolean)]", 51, false, 0.0,0.0,0.0,0,642)
DeclareAlias2("booleanToReal.u", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "hysteresis.y", 1, 5, 51, 65)
DeclareParameter("booleanToReal.realTrue", "Output signal for true Boolean input [W]",\
 49, -6000, 0.0,0.0,0.0,0,560)
DeclareParameter("booleanToReal.realFalse", "Output signal for false Boolean input [W]",\
 50, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("booleanToReal.y", "Connector of Real output signal [W]", \
"prescribedHeatFlow.Q_flow", 1, 5, 50, 0)
DeclareAlias2("booleanToReal1.u", "Connector of Boolean input signal [:#(type=Boolean)]",\
 "Gear_unit_T_range.y", 1, 5, 52, 65)
DeclareParameter("booleanToReal1.realTrue", "Output signal for true Boolean input [m3/s]",\
 51, 6E-05, 0.0,0.0,0.0,0,560)
DeclareParameter("booleanToReal1.realFalse", "Output signal for false Boolean input [m3/s]",\
 52, 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("booleanToReal1.y", "Connector of Real output signal [m3/s]", \
"volumeFlow.V_flow", 1, 5, 49, 0)
DeclareParameter("Gear_unit_T_range.uLow", "If y=true and u<uLow, switch to y=false",\
 53, 313.15, 0.0,0.0,0.0,0,560)
DeclareParameter("Gear_unit_T_range.uHigh", "If y=false and u>uHigh, switch to y=true",\
 54, 333.15, 0.0,0.0,0.0,0,560)
DeclareParameter("Gear_unit_T_range.pre_y_start", "Value of pre(y) at initial time [:#(type=Boolean)]",\
 55, false, 0.0,0.0,0.0,0,562)
DeclareAlias2("Gear_unit_T_range.u", "[K]", "Gear_wall_capacitance.T", 1, 1, 5, 0)
DeclareVariable("Gear_unit_T_range.y", "[:#(type=Boolean)]", 52, false, 0.0,0.0,\
0.0,0,642)
DeclareParameter("Gear_wall_capacitance.C", "Heat capacity of element (= cp*m) [J/K]",\
 56, 3000, 0.0,0.0,0.0,0,560)
DeclareState("Gear_wall_capacitance.T", "Temperature of element [K|degC]", 5, \
376.478, 0.0,1E+100,300.0,0,560)
DeclareDerivative("Gear_wall_capacitance.der(T)", "der(Temperature of element) [K/s]",\
 5, 0.736967, 0.0,0.0,0.0,0,512)
DeclareAlias2("Gear_wall_capacitance.der_T", "Time derivative of temperature (= der(T)) [K/s]",\
 "Gear_wall_capacitance.der(T)", 1, 6, 5, 0)
DeclareAlias2("Gear_wall_capacitance.port.T", "Port temperature [K|degC]", \
"Gear_wall_capacitance.T", 1, 1, 5, 4)
DeclareVariable("Gear_wall_capacitance.port.Q_flow", "Heat flow rate (positive if flowing from outside into the component) [W]",\
 86, 0.0, 0.0,0.0,0.0,0,776)
DeclareParameter("medium.rho", "Density [kg/m3|g/cm3]", 57, 999.7, 0.0,1E+100,\
0.0,0,560)
DeclareParameter("medium.cp", "Specific heat capacity at constant pressure [J/(kg.K)]",\
 58, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("medium.cv", "Specific heat capacity at constant volume [J/(kg.K)]",\
 59, 4192.0, 0.0,0.0,0.0,0,560)
DeclareParameter("medium.lambda", "Thermal conductivity [W/(m.K)]", 60, 0.588, \
0.0,0.0,0.0,0,560)
DeclareParameter("medium.nu", "Kinematic viscosity [m2/s]", 61, 1.307E-06, 0.0,\
1E+100,0.0,0,560)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
preD(DYNX(W_,52),"Gear_unit_T_range.y", false, 0);
preD(DYNX(W_,51),"hysteresis.y", false, 1);
EndPreBlock
StartEqBlock
if (final_==2) {
DYNX(W_,77) = DYNX(DP_,32);
}
DoRemember_(DYNX(W_,74), 0.0, 0);
DoRememAcc_(DYNX(W_,75), 0.8, 4);
DoRemember_(DYNX(W_,83), 0.0, 1);
DoRememAcc_(DYNX(W_,85), 0, 5);
DoRemember_(DYNX(F_,5), 0.736967, 2);
DoRemember_(DYNX(F_,0), 0.0, 3);
DoRememAcc_(DYNX(W_,77), DYNX(DP_,32), 6);
EndEqBlock
EndDataBlock
